/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jerikc_android_demo_camera_LibyuvCore */

#ifndef _Included_com_jerikc_android_demo_camera_LibyuvCore
#define _Included_com_jerikc_android_demo_camera_LibyuvCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jerikc_android_demo_camera_LibyuvCore
 * Method:    ConvertToI420
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_jerikc_android_demo_camera_LibyuvCore_ConvertToI420
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_jerikc_android_demo_camera_LibyuvCore
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jerikc_android_demo_camera_LibyuvCore_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jerikc_android_demo_camera_LibyuvCore
 * Method:    release
 * Signature: (V)V
 */
JNIEXPORT void JNICALL Java_com_jerikc_android_demo_camera_LibyuvCore_release(JNIEnv* , jobject);

#ifdef __cplusplus
}
#endif
#endif
